### ISSUE TITLE
图表无法正常显示

### ISSUE THREAD

**Issue by songhao8080** [chenjiandongx/cutecharts#3]
jupyter-lab
无法运行的 notebook 无法正常显示

![image](https://user-images.githubusercontent.com/10607039/66726064-be1c1900-ee69-11e9-8d75-fad7d669cf88.png)

如果直接运行 ipython notebook 生成的notebook 可以正常显示

![image](https://user-images.githubusercontent.com/10607039/66726072-c7a58100-ee69-11e9-9578-69dc7a88bcb5.png)

**Comment by chenjiandongx** [comment]
是的，目前还没基于 JupyterLab 做适配

**Comment by josangmi** [comment]
期待，这样vscode原生的就能用了。

**Comment by chenjiandongx** [comment]
请更新到 v1.1.0 版本，已可以使用 JupyterLab

https://github.com/chenjiandongx/cutecharts/blob/master/README.md
