### ISSUE TITLE
使用汉字手写体

### ISSUE THREAD

**Issue by dstang2000** [chenjiandongx/cutecharts#8]
原系统中使用的是xkcd这样的名称，它是用内嵌的字体的，见
[https://github.com/timqian/chart.xkcd/blob/master/src/utils/addFont.js](https://github.com/timqian/chart.xkcd/blob/master/src/utils/addFont.js)
我试着加上以下的手写汉字字体（851是可以免费下载的）。
```
		<style>
		@font-face
		{
			font-family: xkcd;
			src: url('851.ttf') format('truetype');
			font-weight:bold;
		}
		</style>
```
但是有的部分（如图表标题、鼠标指上去后变手写体），有的部分却不变（如刻度上的汉字仍为黑体）。不知为什么？
（我想插入个截图在这里，但插入总是不成功，被墙了？）

**Comment by chenjiandongx** [comment]
这个问题你可以 link 到 https://github.com/timqian/chart.xkcd，顺便 @ 一下作者问问
